//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanumanInstitute.Encoder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HanumanInstitute.Encoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null or empty..
        /// </summary>
        internal static string ArgNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; specified by Config.Avs2PipeModPath is not found..
        /// </summary>
        internal static string Avs2PipeModPathNotFound {
            get {
                return ResourceManager.GetString("Avs2PipeModPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one video or audio codec..
        /// </summary>
        internal static string CodecNullOrEmpty {
            get {
                return ResourceManager.GetString("CodecNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EncodeApp &quot;{0}&quot; is not valid. You must specify a member of the EncodeApp class or supply a custom IFileInfoParserFactory that supports additional applications..
        /// </summary>
        internal static string EncodeAppInvalid {
            get {
                return ResourceManager.GetString("EncodeAppInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance of ProcessWorker is busy. You can run concurrent commands by creating other class instances..
        /// </summary>
        internal static string ProcessWorkerBusy {
            get {
                return ResourceManager.GetString("ProcessWorkerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specifiy either videoFile or audioFile..
        /// </summary>
        internal static string VideoFileAndAudioFileNull {
            get {
                return ResourceManager.GetString("VideoFileAndAudioFileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; specified by Config.VsPipePath is not found..
        /// </summary>
        internal static string VsPipePathNotFound {
            get {
                return ResourceManager.GetString("VsPipePathNotFound", resourceCulture);
            }
        }
    }
}
